name: Generate ATT&CK Data

on:
  schedule:
    - cron: "0 3 * * *"

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Set up Python Environment
      uses: actions/setup-python@v1
      with:
        python-version: 3.8
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -U -r ./generateattcks/requirements.txt
    - name: Generate ATTCK Data
      env:
        GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      run: |
        python ./generateattcks/run.py
    - name: Commit files
      run: |
        git config --local user.email "action@github.com"
        git config --local user.name "GitHub Action"
        git add "generated_attck_data.json"
        git commit -m "Adding daily generated_attck_data"
    - name: Push changes
      uses: ad-m/github-push-action@master
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}