name: Testing pyattck

on: 
  push

jobs:
  build:

    runs-on: ${{ matrix.os }}
    strategy:
        matrix:
            os: [windows-latest, ubuntu-latest, macos-latest]
            python-version: [3.6, 3.7, 3.8, 3.9]

    steps:
    - uses: actions/checkout@v2
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v1
      with:
        python-version: ${{ matrix.python-version }}
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -U -r requirements.txt
        pip install -r test-requirements.txt
    - if: matrix.os == 'ubuntu-latest'
      name: Run Tests on Ubuntu
      run: |
        sudo python -m pytest
    - if: matrix.os == 'macos-latest'
      name: Run Tests on macOS
      run: |
        sudo python -m pytest
    - if: matrix.os == 'windows-latest'
      name: Run Tests on Windows
      run: |
        runas /user:administrator python -m pytest
    - if: matrix.os == 'ubuntu-latest'
      name: Code Coverage on Ubuntu
      run: |
        sudo python -m coverage run -m pytest
        sudo python -m coverage report
    - if: matrix.os == 'macos-latest'
      name: Code Coverage on macOS
      run: |
        sudo python -m coverage run -m pytest
        sudo python -m coverage report
    - if: matrix.os == 'windows-latest'
      name: Code Coverage on Windows
      run: |
        runas /user:administrator python -m coverage run -m pytest
        runas /user:administrator python -m coverage report
